[project]
name = 'bryle'
version = "0.0.0"
dependencies = [
  'pillow>=12.1.0',
]

[project.optional-dependencies]
dev = [
  'flake8-pyproject==1.2.*',
  'flake8-simplify==0.30.*',
  'mypy==1.19.*',
  'pytest-cov==7.0.*',
]

[project.scripts]
p = "bryle:main"
bra = "bryle:main"

[tool.setuptools]
packages = ["bryle"]
