---

name: test

'on':
  push:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'
          cache: pip

      - uses: extractions/setup-just@v3

      - run: pip install -r requirements-dev.txt

      - run: just test -v

      - run: just type

      - run: just lint --exit-zero

      - name: print env
        run: env | sort


  update-manual:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.13'
          cache: pip

      - uses: extractions/setup-just@v3

      - run: pip install -r requirements.txt

      - name: re-generate cli output examples in readme file
        run: just update-manual

      - name: install imagemagick
        uses: mfinelli/setup-imagemagick@v7.0.1

      - name: ':memo: update screenshot'
        run: just take-screenshot

      - name: upload screenshot as github artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          path: screenshot.png

      - name: see if something changed
        id: changed
        run: |
          chg=$(git diff --shortstat | wc -l)
          echo "changed=${chg}" >> ${GITHUB_OUTPUT}

      - name: show changes
        if: steps.changed.outputs.changed != '0'
        run: git diff

      - name: commit changes
        if: steps.changed.outputs.changed != '0'
        env:
          GIT_MAIL: >-
            41898282+github-actions[bot]@users.noreply.github.com
        run: |
          git config user.email "${GIT_MAIL}"
          git config user.name "github-actions[bot]"
          git add readme.md screenshot.png
          git commit -m ":memo: update usage instructions && examples"
          git push

...
